/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookstore.GUI;

import bookstore.BLL.BaoCaoDTBLL;
import bookstore.BLL.BaoCaoPNBLL;
import bookstore.BLL.BaoCaoPXBLL;
import bookstore.Entity.BaoCaoDT;
import bookstore.Entity.BaoCaoPN;
import bookstore.Entity.BaoCaoPX;
import com.toedter.calendar.JDateChooser;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;

/**
 *
 * 
 */
public final class frmBaoCao extends javax.swing.JFrame {

    private final BaoCaoPNBLL objpn = new BaoCaoPNBLL();
    private ArrayList<BaoCaoPN> lstpn = new ArrayList<>();
    private final BaoCaoPXBLL objpx = new BaoCaoPXBLL();
    private ArrayList<BaoCaoPX> lstpx = new ArrayList<>();
    private final BaoCaoDTBLL objdt = new BaoCaoDTBLL();
    private ArrayList<BaoCaoDT> lstdt = new ArrayList<>();

    /**
     * Creates new form frmBaoCao
     */
    public frmBaoCao() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("imgs/library.png")).getImage());
        ManagerRadioButton();
        setDefaultCloseOperation(HIDE_ON_CLOSE);
    }

    void ManagerRadioButton() {
        ButtonGroup group = new ButtonGroup();
        group.add(rdbNhap);
        group.add(rdbXuat);
        group.add(rdbDoanhSo);
        rdbNhap.setSelected(true);
        jdcBatDau.setDateFormatString("MM/dd/yyyy");
        jdcKetThuc.setDateFormatString("MM/dd/yyyy");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        popupMenu1 = new java.awt.PopupMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jdcKetThuc = new com.toedter.calendar.JDateChooser();
        jdcBatDau = new com.toedter.calendar.JDateChooser();
        ckbKetThuc = new javax.swing.JCheckBox();
        ckbBatDau = new javax.swing.JCheckBox();
        rdbNhap = new javax.swing.JRadioButton();
        rdbXuat = new javax.swing.JRadioButton();
        rdbDoanhSo = new javax.swing.JRadioButton();
        btnXacNhan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHienThi = new javax.swing.JTable();
        lbtenBC = new javax.swing.JLabel();
        lbDate = new javax.swing.JLabel();
        lbHienThi1 = new javax.swing.JLabel();
        lbHienThi2 = new javax.swing.JLabel();
        lbHienThi3 = new javax.swing.JLabel();
        lbNgayLap = new javax.swing.JLabel();
        btnInBaoCao = new javax.swing.JButton();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Báo Cáo | Phần Mềm Quản Lý Nhà Sách Tuấn Hằng");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setForeground(new java.awt.Color(204, 255, 255));

        jdcKetThuc.setDateFormatString("MM/dd/yyyy");
        jdcKetThuc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jdcBatDau.setDateFormatString("MM/dd/yyyy");
        jdcBatDau.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        ckbKetThuc.setText("Ngày Kết Thúc");

        ckbBatDau.setText("Ngày Bắt Đầu");

        rdbNhap.setText("Báo Cáo Nhập Hàng");

        rdbXuat.setText("Báo Cáo Bán Hàng");

        rdbDoanhSo.setText("Báo Cáo Doanh Thu");

        btnXacNhan.setText("Xác Nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdcBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbBatDau))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbKetThuc)
                    .addComponent(jdcKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbNhap)
                            .addComponent(rdbDoanhSo))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdbXuat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(btnXacNhan)
                        .addGap(54, 54, 54))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {rdbDoanhSo, rdbNhap, rdbXuat});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbNhap)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbXuat)
                            .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(rdbDoanhSo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckbKetThuc)
                            .addComponent(ckbBatDau))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdcKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdcBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tbHienThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbHienThi);

        lbtenBC.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        lbHienThi1.setText("_");

        lbHienThi2.setText("_");

        lbHienThi3.setText("_");

        lbNgayLap.setText("_");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbDate)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(lbtenBC))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbHienThi1)
                        .addGap(159, 159, 159)
                        .addComponent(lbHienThi2)
                        .addGap(164, 164, 164)
                        .addComponent(lbHienThi3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbNgayLap)
                .addGap(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbtenBC)
                .addGap(2, 2, 2)
                .addComponent(lbDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbHienThi2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbHienThi3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbHienThi1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        btnInBaoCao.setText("In Báo Cáo");
        btnInBaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInBaoCaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(btnInBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnInBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String formatDate(JDateChooser date) {
        String res = "";
        SimpleDateFormat df = new SimpleDateFormat("MM/dd/yyyy");
        try {
            res = df.format(date.getDate());
        } catch (Exception e) {
        }
        if (res.equals("")) {

            return null;
        }
        return res;
    }

    boolean checkDate(JDateChooser d1, JDateChooser d2) {
        if (formatDate(d2) == null || formatDate(d1) == null) {
            return false;
        }
        if (ckbBatDau.isSelected() && ckbKetThuc.isSelected() && jdcKetThuc.getDate().compareTo(jdcBatDau.getDate()) < 0) {
            return true;
        }
        return false;
    }

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        if (checkDate(jdcBatDau, jdcKetThuc)) {
            JOptionPane.showMessageDialog(this, "Ngày kết thúc không thể nhỏ hơn ngày bắt đầu!");
            return;
        }
        String w = "";
        if (rdbNhap.isSelected()) {
            lbtenBC.setText("Báo Cáo Nhập Hàng");
            if (ckbBatDau.isSelected() && ckbKetThuc.isSelected()) {
                if (formatDate(jdcBatDau) == null || formatDate(jdcKetThuc) == null) {
                    JOptionPane.showMessageDialog(this, "1.Bỏ tùy chọn nhập\n2.Nhập lại đúng định dạng", "Sai định dạng kiểu Date", 1);
                    return;
                }
                w = "ngayNhap >= '" + formatDate(jdcBatDau) + "' and ngayNhap <= '" + formatDate(jdcKetThuc) + "'";
                binDataPN(w, "soLuongSach DESC");
            } else if (ckbBatDau.isSelected()) {
                if (formatDate(jdcBatDau) == null) {
                    JOptionPane.showMessageDialog(this, "1.Bỏ tùy chọn nhập\n2.Nhập lại đúng định dạng", "Sai định dạng kiểu Date", 1);
                    return;
                }
                w = "ngayNhap >= '" + formatDate(jdcBatDau) + "'";
                binDataPN(w, "soLuongSach DESC");
            } else if (ckbKetThuc.isSelected()) {
                if (formatDate(jdcKetThuc) == null) {
                    JOptionPane.showMessageDialog(this, "1.Bỏ tùy chọn nhập\n2.Nhập lại đúng định dạng", "Sai định dạng kiểu Date", 1);
                    return;
                }
                w = "ngayNhap <= '" + formatDate(jdcKetThuc) + "'";
                binDataPN(w, "soLuongSach DESC");
            } else {
                binDataPN("", "soLuongSach DESC");
            }
        } else if (rdbXuat.isSelected()) {
            lbtenBC.setText("Báo Cáo Bán Hàng");
            if (ckbBatDau.isSelected() && ckbKetThuc.isSelected()) {
                if (formatDate(jdcBatDau) == null || formatDate(jdcKetThuc) == null) {
                    JOptionPane.showMessageDialog(this, "1.Bỏ tùy chọn nhập\n2.Nhập lại đúng định dạng", "Sai định dạng kiểu Date", 1);
                    return;
                }
                w = "ngayXuat >= '" + formatDate(jdcBatDau) + "' and ngayXuat <= '" + formatDate(jdcKetThuc) + "'";
                binDataPX(w, "soLuongSach DESC");
            } else if (ckbBatDau.isSelected()) {
                if (formatDate(jdcBatDau) == null) {
                    JOptionPane.showMessageDialog(this, "1.Bỏ tùy chọn nhập\n2.Nhập lại đúng định dạng", "Sai định dạng kiểu Date", 1);
                    return;
                }
                w = "ngayXuat >= '" + formatDate(jdcBatDau) + "'";
                binDataPX(w, "soLuongSach DESC");
            } else if (ckbKetThuc.isSelected()) {
                if (formatDate(jdcKetThuc) == null) {
                    JOptionPane.showMessageDialog(this, "1.Bỏ tùy chọn nhập\n2.Nhập lại đúng định dạng", "Sai định dạng kiểu Date", 1);
                    return;
                }
                w = "ngayXuat <= '" + formatDate(jdcKetThuc) + "'";
                binDataPX(w, "soLuongSach DESC");
            } else {
                binDataPX("", "soLuongSach DESC");
            }
        } else if (ckbBatDau.isSelected() && ckbKetThuc.isSelected()) {
            lbtenBC.setText("Báo Cáo Doanh Thu");
            if (formatDate(jdcBatDau) == null || formatDate(jdcKetThuc) == null) {
                JOptionPane.showMessageDialog(this, "1.Bỏ tùy chọn nhập\n2.Nhập lại đúng định dạng", "Sai định dạng kiểu Date", 1);
                return;
            }
            String w1 = "'" + formatDate(jdcBatDau) + "'";
            String w2 = "'" + formatDate(jdcKetThuc) + "'";
            binDataDT(w1, w2);
        } else if (ckbBatDau.isSelected()) {
            lbtenBC.setText("Báo Cáo Doanh Thu");
            if (formatDate(jdcBatDau) == null) {
                JOptionPane.showMessageDialog(this, "1.Bỏ tùy chọn nhập\n2.Nhập lại đúng định dạng", "Sai định dạng kiểu Date", 1);
                return;
            }
            String w1 = "'" + formatDate(jdcBatDau) + "'";
            binDataDT(w1, "");
        } else if (ckbKetThuc.isSelected()) {
            lbtenBC.setText("Báo Cáo Doanh Thu");
            if (formatDate(jdcKetThuc) == null) {
                JOptionPane.showMessageDialog(this, "1.Bỏ tùy chọn nhập\n2.Nhập lại đúng định dạng", "Sai định dạng kiểu Date", 1);
                return;
            }
            String w2 = "'" + formatDate(jdcKetThuc) + "'";
            binDataDT("", w2);
        } else {
            lbtenBC.setText("Báo Cáo Doanh Thu");
            binDataDT("", "");
        }

        DateTimeFormatter df = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime date = LocalDateTime.now();
        lbNgayLap.setText("Ngày lập: " + df.format(date));
        String time = "";
        if (ckbBatDau.isSelected()) {
            time += formatDate(jdcBatDau);
        }
        time += " - ";
        if (ckbKetThuc.isSelected()) {
            time += formatDate(jdcKetThuc);
        }
        lbDate.setText(time);

    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        new frmHeThong().setVisible(true);
    }//GEN-LAST:event_formWindowClosing


    private void btnInBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInBaoCaoActionPerformed
        // TODO add your handling code here:
        String s = "";
        try {
            s = tbHienThi.getValueAt(0, 0).toString();
            System.out.println("xxx: " + s);

        } catch (Exception e) {
        }
        if (s.equals("")) {
            JOptionPane.showMessageDialog(this, "Không có dữ liệu để in!");
            return;
        }
        JFileChooser fc = new JFileChooser();
        int option = fc.showSaveDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            String filename = fc.getSelectedFile().getName();
            String path = fc.getSelectedFile().getParentFile().getPath();
            int len = filename.length();
            String ext = "";
            String file = "";

            if (len > 4) {
                ext = filename.substring(len - 4, len);
            }

            if (ext.equals(".xls")) {
                file = path + "\\" + filename;
            } else {
                file = path + "\\" + filename + ".xls";
            }
            try {
                toExcel(tbHienThi, new File(file));
                if (JOptionPane.showConfirmDialog(this, "Mở file?", "Xuất file thành công!!!", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    File f = new File(file);
                    try {
                        Desktop.getDesktop().open(f);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
            } catch (IOException ex) {
                Logger.getLogger(frmSach.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Xuất file không thành công!");
            }
        }
    }//GEN-LAST:event_btnInBaoCaoActionPerformed

    void binDataDT(String d1, String d2) {
        lstdt = objdt.getAll(d1, d2);
        Vector col = new Vector();
        col.add("Mã Sách");
        col.add("Tiêu Đề");
        col.add("Giá Bìa");
        col.add("Số Lượng Tồn");
        col.add("Gian Hàng");
        col.add("Số Lượng Nhập");
        col.add("Tiền Nhập");
        col.add("Số Lượng Bán");
        col.add("Tiền Bán");
        col.add("Doanh Thu");
        int tienNhap = 0, tienBan = 0;
        Vector data = new Vector();
        for (BaoCaoDT i : lstdt) {
            tienNhap += i.getTienNhap();
            tienBan += i.getTienBan();
            Vector row = new Vector();
            row.add(i.getMaSach());
            row.add(i.getTieuDe());
            row.add(i.getGiaBia());
            row.add(i.getSoLuongTon());
            row.add(i.getGianHang());
            row.add(i.getSlNhap());
            row.add(i.getTienNhap());
            row.add(i.getSlXuat());
            row.add(i.getTienBan());
            row.add(i.getTienLai());
            data.add(row);
        }
        DefaultTableModel dtm = new DefaultTableModel(data, col);
        tbHienThi.setModel(dtm);
        lbHienThi1.setText("Tổng số tiền nhập vào: " + String.valueOf(tienNhap) + " VNĐ");
        lbHienThi2.setText("Tổng số tiền bán ra: " + String.valueOf(tienBan) + " VNĐ");
        lbHienThi3.setText("Tổng số tiền lãi: " + String.valueOf(tienBan - tienNhap) + " VNĐ");
    }

    void binDataPN(String w, String o) {
        lstpn = objpn.getAll(w, o);
        Vector col = new Vector();
        col.add("Mã Phiếu Nhập");
        col.add("Nhà Xuất Bản");
        col.add("Ngày Nhập");
        col.add("Số Lượng Sách");
        col.add("Thành Tiền");
        int soLuong = 0, thanhTien = 0;
        Vector data = new Vector();
        for (BaoCaoPN i : lstpn) {
            soLuong += i.getSoLuongSach();
            thanhTien += i.getThanhTien();
            Vector row = new Vector();
            row.add(i.getMaPhieuNhap());
            row.add(i.getNhaXuatBan());
            row.add(i.getNgayNhap());
            row.add(i.getSoLuongSach());
            row.add(i.getThanhTien());
            data.add(row);
        }
        DefaultTableModel dtm = new DefaultTableModel(data, col);
        tbHienThi.setModel(dtm);
        lbHienThi1.setText("Tổng số phiếu nhập: " + String.valueOf(lstpn.size()));
        lbHienThi2.setText("Tổng số sách nhập: " + String.valueOf(soLuong) + " cuốn");
        lbHienThi3.setText("Tổng số tiền: " + String.valueOf(thanhTien) + " VNĐ");
    }

    void binDataPX(String w, String o) {
        lstpx = objpx.getAll(w, o);
        Vector col = new Vector();
        col.add("Mã Phiếu Xuất");
        col.add("tên Khách Hàng");
        col.add("Ngày Xuất");
        col.add("Số Lượng Sách");
        col.add("Thành Tiền");
        int soLuong = 0, thanhTien = 0;
        Vector data = new Vector();
        for (BaoCaoPX i : lstpx) {
            soLuong += i.getSoLuongSach();
            thanhTien += i.getThanhTien();
            Vector row = new Vector();
            row.add(i.getMaPhieuXuat());
            row.add(i.getTenKH());
            row.add(i.getNgayXuat());
            row.add(i.getSoLuongSach());
            row.add(i.getThanhTien());
            data.add(row);
        }
        DefaultTableModel dtm = new DefaultTableModel(data, col);
        tbHienThi.setModel(dtm);
        lbHienThi1.setText("Tổng số phiếu xuất: " + String.valueOf(lstpx.size()));
        lbHienThi2.setText("Tổng số sách bán: " + String.valueOf(soLuong) + " cuốn");
        lbHienThi3.setText("Tổng số tiền: " + String.valueOf(thanhTien) + " VNĐ");
    }

    void toExcel(JTable table, File file) throws IOException {
        String sheetName = "Sheet1";//name of sheet
        HSSFWorkbook wb = new HSSFWorkbook();
        HSSFSheet sheet = wb.createSheet(sheetName);
        TableModel model = table.getModel();

        // Make report name
        HSSFRow row = sheet.createRow(3);
        HSSFCell cell = row.createCell(3);
        cell.setCellValue(lbtenBC.getText());

        //Make date 
        row = sheet.createRow(5);
        cell = row.createCell(4);
        cell.setCellValue(lbDate.getText());
//        Get col name
        row = sheet.createRow(7);
        cell = row.createCell(0);
        cell.setCellValue("STT");
        for (int i = 0; i < model.getColumnCount(); i++) {
            cell = row.createCell(i + 1);
            cell.setCellValue(model.getColumnName(i).toString());
        }
//        iterating r number of rows
        for (int r = 0; r < model.getRowCount(); r++) {
            row = sheet.createRow(r + 8);
            cell = row.createCell(0);
            cell.setCellValue(r + 1);
            //iterating c number of columns
            for (int c = 0; c < model.getColumnCount(); c++) {
                cell = row.createCell(c + 1);
                cell.setCellValue(model.getValueAt(r, c).toString());
            }
        }
        row = sheet.createRow(9 + model.getRowCount());
        cell = row.createCell(0);
        cell.setCellValue(lbHienThi1.getText());
        cell = row.createCell(3);
        cell.setCellValue(lbHienThi2.getText());
        cell = row.createCell(6);
        cell.setCellValue(lbHienThi3.getText());
        row = sheet.createRow(10 + model.getRowCount());
        cell = row.createCell(5);
        cell.setCellValue(lbNgayLap.getText());

        FileOutputStream fileOut = new FileOutputStream(file);

        //write this workbook to an Outputstream.
        wb.write(fileOut);
        fileOut.flush();
        fileOut.close();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBaoCao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBaoCao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBaoCao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBaoCao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBaoCao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInBaoCao;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox ckbBatDau;
    private javax.swing.JCheckBox ckbKetThuc;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcBatDau;
    private com.toedter.calendar.JDateChooser jdcKetThuc;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbHienThi1;
    private javax.swing.JLabel lbHienThi2;
    private javax.swing.JLabel lbHienThi3;
    private javax.swing.JLabel lbNgayLap;
    private javax.swing.JLabel lbtenBC;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JRadioButton rdbDoanhSo;
    private javax.swing.JRadioButton rdbNhap;
    private javax.swing.JRadioButton rdbXuat;
    private javax.swing.JTable tbHienThi;
    // End of variables declaration//GEN-END:variables
}
