/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookstore.GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * 
 */
public class frmHeThong extends javax.swing.JFrame {

    /**
     * Creates new form frmHeThong
     */
    public frmHeThong() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("imgs/library.png")).getImage());
      
        getDate();
    }

    void getDate() {
        Timer timer = new Timer(500, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                binDate();
            }
        });
        timer.setRepeats(true);
        timer.setCoalesce(true);
        timer.setInitialDelay(0);
        timer.start();
    }

    void binDate() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy | HH:mm:ss");
        lbDate.setText(sdf.format(new Date()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnQLNXB = new javax.swing.JButton();
        btnQLGH = new javax.swing.JButton();
        btnQLNhap = new javax.swing.JButton();
        btnQLSach = new javax.swing.JButton();
        btnQLXuat = new javax.swing.JButton();
        lbDoiMatKhau = new javax.swing.JLabel();
        btnQLNhap1 = new javax.swing.JButton();
        lbDate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần Mềm Quản Lý Nhà Sách Tuấn Hằng");
        setLocation(new java.awt.Point(250, 100));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("PHẦN MỀM QUẢN LÝ NHÀ SÁCH TUẤN HẰNG");

        btnQLNXB.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnQLNXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore/GUI/imgs/kisspng-vector-graphics-cargo-truck-transport-5cf47287f2bdf5.3636572815595239759943.png"))); // NOI18N
        btnQLNXB.setToolTipText("");
        btnQLNXB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLNXB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLNXB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLNXBMouseClicked(evt);
            }
        });

        btnQLGH.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnQLGH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore/GUI/imgs/114533c4243185a7d028ef98b3205679.png"))); // NOI18N
        btnQLGH.setToolTipText("");
        btnQLGH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLGH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLGH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLGHMouseClicked(evt);
            }
        });
        btnQLGH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLGHActionPerformed(evt);
            }
        });

        btnQLNhap.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnQLNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore/GUI/imgs/transparent-arrow-5d714bc4ad65f5.8319074215677060527102.png"))); // NOI18N
        btnQLNhap.setToolTipText("");
        btnQLNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLNhap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLNhapMouseClicked(evt);
            }
        });
        btnQLNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNhapActionPerformed(evt);
            }
        });

        btnQLSach.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnQLSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore/GUI/imgs/book-11549420966kupbnxvyyl.png"))); // NOI18N
        btnQLSach.setToolTipText("");
        btnQLSach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLSach.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLSachMouseClicked(evt);
            }
        });
        btnQLSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSachActionPerformed(evt);
            }
        });

        btnQLXuat.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnQLXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore/GUI/imgs/2331966.png"))); // NOI18N
        btnQLXuat.setToolTipText("");
        btnQLXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLXuatMouseClicked(evt);
            }
        });
        btnQLXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLXuatActionPerformed(evt);
            }
        });

        lbDoiMatKhau.setBackground(new java.awt.Color(102, 204, 255));
        lbDoiMatKhau.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        lbDoiMatKhau.setForeground(new java.awt.Color(0, 153, 255));
        lbDoiMatKhau.setText("Đổi mật khẩu");
        lbDoiMatKhau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDoiMatKhauMouseClicked(evt);
            }
        });

        btnQLNhap1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnQLNhap1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore/GUI/imgs/images (1).png"))); // NOI18N
        btnQLNhap1.setToolTipText("");
        btnQLNhap1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQLNhap1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLNhap1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLNhap1MouseClicked(evt);
            }
        });
        btnQLNhap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNhap1ActionPerformed(evt);
            }
        });

        lbDate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbDate.setText("Ngày");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Quản lý Nhà Cung Cấp");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Quản Lý Danh Mục");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Quản Lý Đơn Hàng");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Quản Lý Sách");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Báo Cáo - Thống Kê");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Quản Lý Nhập Hàng");
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbDoiMatKhau)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(136, 136, 136))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnQLNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQLSach, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel2)))
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQLGH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(btnQLNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8))
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(btnQLNhap1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQLXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnQLGH, btnQLNXB, btnQLNhap, btnQLNhap1, btnQLXuat});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnQLSach, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnQLXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnQLGH, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnQLNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addComponent(btnQLNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnQLNhap1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDate)
                    .addComponent(lbDoiMatKhau))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnQLGH, btnQLNhap, btnQLNhap1, btnQLSach, btnQLXuat});

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void btnQLNXBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLNXBMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new frmNhaXuatBan().setVisible(true);
    }//GEN-LAST:event_btnQLNXBMouseClicked

    private void btnQLGHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLGHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQLGHActionPerformed

    private void btnQLGHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLGHMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new frmGianHang().setVisible(true);
    }//GEN-LAST:event_btnQLGHMouseClicked

    private void btnQLSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQLSachActionPerformed

    private void btnQLSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLSachMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new frmSach().setVisible(true);
    }//GEN-LAST:event_btnQLSachMouseClicked

    private void btnQLNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLNhapMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new frmQLNhap().setVisible(true);
    }//GEN-LAST:event_btnQLNhapMouseClicked

    private void btnQLXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLXuatMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new frmQLXuat().setVisible(true);
    }//GEN-LAST:event_btnQLXuatMouseClicked

    private void lbDoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDoiMatKhauMouseClicked
        // TODO add your handling code here:
//        new frmDoiMatKhau().setVisible(true);
        new jdDoiMatKhau(this, true).setVisible(true);
    }//GEN-LAST:event_lbDoiMatKhauMouseClicked

    private void btnQLNhap1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLNhap1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQLNhap1MouseClicked

    private void btnQLXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQLXuatActionPerformed

    private void btnQLNhap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNhap1ActionPerformed
        // TODO add your handling code here:
        new frmBaoCao().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnQLNhap1ActionPerformed

    private void btnQLNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQLNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHeThong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHeThong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHeThong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHeThong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHeThong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQLGH;
    private javax.swing.JButton btnQLNXB;
    private javax.swing.JButton btnQLNhap;
    private javax.swing.JButton btnQLNhap1;
    private javax.swing.JButton btnQLSach;
    private javax.swing.JButton btnQLXuat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbDoiMatKhau;
    // End of variables declaration//GEN-END:variables
}
