/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookstore.GUI;

import bookstore.BLL.CTPXBLL;
import bookstore.BLL.PhieuXuatBLL;
import bookstore.BLL.SachBLL;
import bookstore.Entity.CTPX;
import bookstore.Entity.PhieuXuat;
import bookstore.Entity.Sach;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Date;
import java.text.DateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;

/**
 *
 * 
 */
public class jdXuat extends javax.swing.JDialog {

    frmQLXuat obj = new frmQLXuat();
    private PhieuXuatBLL objpx = new PhieuXuatBLL();
    private CTPXBLL objctpx = new CTPXBLL();
    SachBLL objs = new SachBLL();
    ArrayList<Sach> lsts = new ArrayList<>();
    ArrayList<CTPX> lstCTPX = new ArrayList<>();
    ArrayList<String> lstMaSach = new ArrayList<>();
    boolean isEdit = false;

    /**
     * Creates new form jdXuat
     */
    public jdXuat(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setIconImage(new ImageIcon(getClass().getResource("imgs/library.png")).getImage());
        initComponents();
        spnSoLuong.setValue(1);
        binCmbSach();
        getDate();
    }

    public jdXuat(java.awt.Frame parent, boolean modal, boolean _isEdit) {
        super(parent, modal);
        isEdit = _isEdit;
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("imgs/library.png")).getImage());
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        lstCTPX.clear();
        for (CTPX i : obj.lstEditctpx) {
            lstCTPX.add(i);
        }
        for (CTPX i : lstCTPX) {
            lstMaSach.add(i.getMaSach());
        }
        txtTenKH.setText(obj.tenKH);
        btnXacNhan.setText("Sửa Phiếu Xuất");
        spnSoLuong.setValue(1);
        binCmbSach();
        getDate();
        binData(lstCTPX);
    }

    void getDate() {
        Timer timer = new Timer(500, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                binDate();
            }
        });
        timer.setRepeats(true);
        timer.setCoalesce(true);
        timer.setInitialDelay(0);
        timer.start();
    }

    void binDate() {
        lbLich.setText(DateFormat.getDateTimeInstance().format(new java.util.Date()));
    }

    void binCmbSach() {
        cmbSach.removeAllItems();
        lsts = objs.getAll("", "", "");
        for (Sach i : lsts) {
            cmbSach.addItem(i.getTieuDe());
        }
        cmbSach.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        lbLich = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbView = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnXacNhan = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnXoaAll = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbSach = new javax.swing.JComboBox<>();
        spnSoLuong = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLamLai = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tên Khách Hàng");

        lbLich.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbLich.setText("Ngày");

        tbView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbView.setToolTipText("Quản Lý Phiếu Nhập");
        tbView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbViewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbView);

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        btnXacNhan.setText("Thêm Phiếu Xuất");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy Bỏ");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnXoaAll.setText("Xóa Tất Cả");
        btnXoaAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnXacNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoaAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnHuy, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHuy, btnXacNhan, btnXoaAll});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnXoaAll, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnHuy)
                .addGap(19, 19, 19))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnHuy, btnXacNhan, btnXoaAll});

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        btnThem.setText("Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tên Sách");

        cmbSach.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbSach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        spnSoLuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spnSoLuong.setMinimumSize(new java.awt.Dimension(1, 1));
        spnSoLuong.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                spnSoLuongFocusGained(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Số lượng");

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnLamLai.setText("Làm Lại");
        btnLamLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamLaiActionPerformed(evt);
            }
        });

        btnSelect.setText("Xóa Tất Cả");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(btnThem)
                .addGap(50, 50, 50)
                .addComponent(btnSua)
                .addGap(48, 48, 48)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnLamLai, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbSach, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(spnSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLamLai, btnSua, btnThem, btnXoa});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSelect)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua)
                    .addComponent(btnLamLai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLamLai, btnSua, btnThem, btnXoa});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbLich)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbLich)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbViewMouseClicked
        // TODO add your handling code here:
        if (tbView.getSelectedRow() == -1) {
            return;
        }
        //        lsts = objs.getAll("", "", "");
        String item = tbView.getValueAt(tbView.getSelectedRow(), 0).toString();
        for (Sach i : lsts) {
            if (item.equals(i.getMaSach())) {
                item = i.getTieuDe();
                break;
            }
        }
        cmbSach.setSelectedItem(item);
        spnSoLuong.setValue(Integer.parseInt(tbView.getValueAt(tbView.getSelectedRow(), 1).toString()));
    }//GEN-LAST:event_tbViewMouseClicked

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        if (lstCTPX.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Hóa đơn trống!");
            return;
        } else if (txtTenKH.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Hãy nhập tên khách hàng!");
            txtTenKH.requestFocus();
            return;
        } else if (isEdit) {
            PhieuXuat dt = new PhieuXuat();
            dt.setTenKH(txtTenKH.getText());
            String maPX = obj.lstEditctpx.get(0).getMaPhieuXuat();
            dt.setMaPhieuXuat(maPX);
            int thanhTien = 0;
            for (CTPX i : lstCTPX) {
                thanhTien += i.getThanhTien();
            }
            dt.setThanhTien(thanhTien);
            if (JOptionPane.showConfirmDialog(this, "Sửa bản ghi này?", "Thông báo!!!", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                if (objpx.updateData(dt)) {
                    for (CTPX x : lstCTPX) {
                        boolean check = true;
                        x.setMaPhieuXuat(maPX);
                        for (CTPX y : obj.lstEditctpx) {
                            if (x.getMaSach().equals(y.getMaSach())) {
                                check = false;
                                x.setMaCTPX(y.getMaCTPX());
                                //                            System.out.println(x.getMaCTPX() + " " + x.getMaPhieuXuat() + " " + x.getMaSach() + " " + x.getSoLuong() + " " + x.getDonGia() + " " + x.getThanhTien());
                                objctpx.updateData(x);
                                obj.lstEditctpx.remove(y);
                                break;
                            }
                        }
//                        System.out.println(check);
                        if (check) {
//                            System.out.println(obj.getIDCTPX());
                            x.setMaCTPX(obj.getIDCTPX());
                            objctpx.insertData(x);
                        }
                    }
                    for (CTPX y : obj.lstEditctpx) {
                        String id = y.getMaCTPX();
//                        System.out.println("del: " + y.getMaSach());
                        objctpx.deleteData_CTPX(id);
                    }
                    JOptionPane.showMessageDialog(this, "Sửa phiếu xuất thành công!");
                } else {
                    JOptionPane.showMessageDialog(this, "Sửa phiếu xuất thất bại!");
                }
            }

        } else {
            PhieuXuat data = new PhieuXuat();
            String idPX = obj.getIDPX();
            data.setMaPhieuXuat(idPX);
            data.setTenKH(txtTenKH.getText());
            //            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MM/dd/yyyy");
            LocalDate now = LocalDate.now();
            data.setNgayXuat(Date.valueOf(now));
            int thanhTien = 0;
            for (CTPX i : lstCTPX) {
                thanhTien += i.getThanhTien();
            }
            data.setThanhTien(thanhTien);
            if (JOptionPane.showConfirmDialog(this, "Tạo mới phiếu xuất?", "Thông báo!!!", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                if (objpx.insertData(data)) {
                    for (CTPX i : lstCTPX) {
                        //                    System.out.println(obj.getIDCTPX());
                        i.setMaCTPX(obj.getIDCTPX());
                        i.setMaPhieuXuat(idPX);
                        objctpx.insertData(i);
                    }
                    JOptionPane.showMessageDialog(this, "Tạo phiếu xuất thành công!");
                    int dialogResult = JOptionPane.showConfirmDialog(this, "Bạn muốn tạo hóa đơn?", "Thông báo", JOptionPane.YES_NO_OPTION);
                    if (dialogResult == JOptionPane.YES_OPTION) {
                        JFileChooser fc = new JFileChooser();
                        int option = fc.showSaveDialog(this);
                        if (option == JFileChooser.APPROVE_OPTION) {
                            String filename = fc.getSelectedFile().getName();
                            String path = fc.getSelectedFile().getParentFile().getPath();
                            int len = filename.length();
                            String ext = "";
                            String file = "";

                            if (len > 4) {
                                ext = filename.substring(len - 4, len);
                            }

                            if (ext.equals(".xls")) {
                                file = path + "\\" + filename;
                            } else {
                                file = path + "\\" + filename + ".xls";
                            }
                            try {
                                toExcel(data, tbView, new File(file));
                                if (JOptionPane.showConfirmDialog(this, "Mở file?", "Xuất file thành công!!!", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                                    File f = new File(file);
                                    try {
                                        Desktop.getDesktop().open(f);
                                    } catch (IOException e) {
                                        e.printStackTrace();
                                    }
                                }
                            } catch (IOException ex) {
                                Logger.getLogger(frmSach.class.getName()).log(Level.SEVERE, null, ex);
                                JOptionPane.showMessageDialog(this, "Xuất file không thành công!");
                            }
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Tạo phiếu xuất thất bại!");
                }
            }
        }
        this.setVisible(false);
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Bạn muốn hủy thao tác?", "Thông báo!!!", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnXoaAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaAllActionPerformed
        // TODO add your handling code here:
        lstCTPX.removeAll(lstCTPX);
        lstMaSach.removeAll(lstMaSach);
        binData(lstCTPX);
    }//GEN-LAST:event_btnXoaAllActionPerformed

    void binData(ArrayList<CTPX> lst) {
//        lst = nxbdll.getAll(t,w,o);
        Vector col = new Vector();
        col.add("Mã Sách");
        col.add("Số Lượng");
        col.add("Đơn Giá");
        col.add("Thành Tiền");

        Vector data = new Vector();
        for (CTPX i : lst) {
            Vector row = new Vector();
            row.add(i.getMaSach());
            row.add(i.getSoLuong());
            row.add(i.getDonGia());
            row.add(i.getThanhTien());
            data.add(row);
        }
        DefaultTableModel dtm = new DefaultTableModel(data, col);
        tbView.setModel(dtm);
    }

    void clearText() {
        cmbSach.setSelectedIndex(-1);
        spnSoLuong.setValue(1);
        cmbSach.requestFocus();
    }

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        // TODO add your handling code here:

        lsts = objs.getAll("", "", "");
        CTPX data = new CTPX();
        //        System.out.println(lsts.get(cmbSach.getSelectedIndex()).getMaSach());
        try {
            data.setMaSach(lsts.get(cmbSach.getSelectedIndex()).getMaSach());
            for (String i : lstMaSach) {
                if (i.equals(data.getMaSach())) {
                    JOptionPane.showMessageDialog(this, "Sách bạn chọn đã có!");
                    clearText();
                    return;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Hãy lựa chọn sách!");
            clearText();
            return;
        }
        data.setSoLuong((int) spnSoLuong.getValue());
        if (data.getSoLuong() < 1) {
            JOptionPane.showMessageDialog(this, "Số lượng không hợp lệ!");
            spnSoLuong.setValue(1);
            return;
        }
        String w = "maSach = '" + data.getMaSach() + "'";
        lsts = objs.getAll("", w, "");
        if (data.getSoLuong() > lsts.get(0).getSoLuongTon()) {
            JOptionPane.showMessageDialog(this, "Sách trong kho còn " + lsts.get(0).getSoLuongTon() + " cuốn!", "Không đủ sách", 1);
            spnSoLuong.setValue(1);
            return;
        }
        data.setDonGia(lsts.get(0).getGiaBia());
        data.setThanhTien(data.getDonGia() * (data.getSoLuong()));
        lstMaSach.add(data.getMaSach());
        lstCTPX.add(data);
        //        System.out.println(lstCTPX.size() + " " + lstMaSach.size());
        binData(lstCTPX);
        clearText();
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void spnSoLuongFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spnSoLuongFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_spnSoLuongFocusGained

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int i = tbView.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(this, "Chọn bản ghi cần xóa trước!");
            return;
        }
        String s = tbView.getValueAt(i, 0).toString();
        for (int x = 0; x < lstCTPX.size(); x++) {
            if (lstCTPX.get(x).getMaSach().equals(s)) {
                lstCTPX.remove(x);
                break;
            }
        }
        for (int x = 0; x < lstMaSach.size(); x++) {
            if (lstMaSach.get(x).equals(s)) {
                lstMaSach.remove(x);
                break;
            }
        }
        //        System.out.println(lstCTPX.size() + " " + lstMaSach.size());
        binData(lstCTPX);
        clearText();
    }//GEN-LAST:event_btnXoaActionPerformed

    public static void toExcel(PhieuXuat px, JTable table, File file) throws IOException {
        String sheetName = "Sheet1";//name of sheet
        HSSFWorkbook wb = new HSSFWorkbook();
        HSSFSheet sheet = wb.createSheet(sheetName);
        TableModel model = table.getModel();
        HSSFRow row = sheet.createRow(0);
        HSSFCell cell = row.createCell(0);
        cell.setCellValue("Mã Phiếu Xuất");
        cell = row.createCell(1);
        cell.setCellValue(px.getMaPhieuXuat());
        cell = row.createCell(3);
        cell.setCellValue("Ngày xuất");
        cell = row.createCell(4);
        cell.setCellValue(px.getNgayXuat().toString());
        row = sheet.createRow(1);
        cell = row.createCell(0);
        cell.setCellValue("Tên Khách Hàng");
        cell = row.createCell(1);
        cell.setCellValue(px.getTenKH());

//        Get col name
        row = sheet.createRow(3);
        cell = row.createCell(0);
        cell.setCellValue("STT");
        for (int i = 0; i < model.getColumnCount(); i++) {
            cell = row.createCell(i + 1);
            cell.setCellValue(model.getColumnName(i).toString());
        }
//        iterating r number of rows
        for (int r = 0; r < model.getRowCount(); r++) {
            row = sheet.createRow(r + 4);
            cell = row.createCell(0);
            cell.setCellValue(r + 1);
            //iterating c number of columns
            for (int c = 0; c < model.getColumnCount(); c++) {
                cell = row.createCell(c + 1);
                cell.setCellValue(model.getValueAt(r, c).toString());
            }
        }
        row = sheet.createRow(model.getRowCount() + 4);
        cell = row.createCell(model.getColumnCount() - 1);
        cell.setCellValue("Tổng tiền");
        cell = row.createCell(model.getColumnCount());
        cell.setCellValue(px.getThanhTien());

        FileOutputStream fileOut = new FileOutputStream(file);

        //write this workbook to an Outputstream.
        wb.write(fileOut);
        fileOut.flush();
        fileOut.close();
    }
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int i = tbView.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(this, "Chọn bản ghi cần sửa trước!");
            return;
        }
        lsts = objs.getAll("", "", "");
        try {
            lstCTPX.get(i).setMaSach(lsts.get(cmbSach.getSelectedIndex()).getMaSach());
        } catch (Exception e) {
            e.printStackTrace();
        }
        lstMaSach.remove(tbView.getValueAt(i, 0).toString());
        for (String in : lstMaSach) {
            if (in.equals(lstCTPX.get(i).getMaSach())) {
                JOptionPane.showMessageDialog(this, "Mã sách này đã tồn tại!");
                return;
            }
        }
        lstMaSach.add(lstCTPX.get(i).getMaSach());
        lstCTPX.get(i).setSoLuong((int) spnSoLuong.getValue());
        if (lstCTPX.get(i).getSoLuong() < 1) {
            JOptionPane.showMessageDialog(this, "Số lượng không hợp lệ!");
            spnSoLuong.setValue(1);
            return;
        }
        String w = "maSach = '" + lstCTPX.get(i).getMaSach() + "'";
        lsts = objs.getAll("", w, "");
        lstCTPX.get(i).setThanhTien(lstCTPX.get(i).getDonGia() * lstCTPX.get(i).getSoLuong());
        binData(lstCTPX);
        clearText();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLamLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamLaiActionPerformed
        // TODO add your handling code here:
        clearText();
    }//GEN-LAST:event_btnLamLaiActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        // TODO add your handling code here:
        new jdSachSelect(this, true).setVisible(true);
        cmbSach.setSelectedItem(jdSachSelect.idSach);
    }//GEN-LAST:event_btnSelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdXuat dialog = new jdXuat(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLamLai;
    private javax.swing.JButton btnSelect;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaAll;
    private javax.swing.JComboBox<String> cmbSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbLich;
    private javax.swing.JSpinner spnSoLuong;
    private javax.swing.JTable tbView;
    private javax.swing.JTextField txtTenKH;
    // End of variables declaration//GEN-END:variables
}
